name: Push and Pull Request Workflow

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
  
jobs:
  lint:
    name: Run Linter
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Run Linter
        run: ./gradlew --parallel ktlint lint

  unit_tests:
    name: Run Unit Tests
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Check Out
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Unit Tests
        run: ./gradlew --parallel test
